set runtimepath^=$XDG_CONFIG_HOME/vim
set runtimepath+=$XDG_DATA_HOME/vim
set runtimepath+=$XDG_CONFIG_HOME/vim/after

set packpath^=$XDG_DATA_HOME/vim,$XDG_CONFIG_HOME/vim
set packpath+=$XDG_CONFIG_HOME/vim/after,$XDG_DATA_HOME/vim/after

let g:netrw_home = $XDG_DATA_HOME."/vim"
call mkdir($XDG_DATA_HOME."/vim/spell", 'p')

set backupdir=$XDG_STATE_HOME/vim/backup | call mkdir(&backupdir, 'p')
set directory=$XDG_STATE_HOME/vim/swap   | call mkdir(&directory, 'p')
set undodir=$XDG_STATE_HOME/vim/undo     | call mkdir(&undodir,   'p')
set viewdir=$XDG_STATE_HOME/vim/view     | call mkdir(&viewdir,   'p')

if !has('nvim') | set viminfofile=$XDG_STATE_HOME/vim/viminfo | endif


source /usr/share/nvim/archlinux.vim

set ic
set relativenumber
set number
autocmd BufRead ~/.config/i3/* setlocal ft=i3config
let g:airline_powerline_fonts = 1
let g:airline_theme='bubblegum'
let g:code_runner_save_before_execute = 1

" let g:runner_run_key = "<F5>"
" let g:runner_c_executable = "gcc"
" let g:runner_cpp_executable = "g++"

call plug#begin()
Plug 'dracula/vim', { 'as': 'dracula' } 
Plug 'chrisbra/Colorizer'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'tpope/vim-commentary'
Plug 'lambdalisue/suda.vim'
Plug 'xuhdev/SingleCompile'
Plug 'xianzhon/vim-code-runner'
Plug 'tpope/vim-surround'
Plug 'vim-scripts/c.vim'

call plug#end()

set nofoldenable
" set foldmethod=indent
set foldmethod=syntax
nmap <F9> :SCCompile<cr>
nmap <F10> :SCCompileRun<cr> 	
cmap w!! w !sudo tee > /dev/null %



